# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure("2") do |config|

  config.vm.define "base_punch" do |base|
    #base.vm.box = "envimation/ubuntu-xenial"
    base.vm.box = "bento/ubuntu-16.04"    

    # Set the needed config for installing VirtualBox Guest Additions later in the make file    
    base.vbguest.auto_update = false
    base.vbguest.iso_mount_point = "/tmp/mount"    

    # Set the name of the VM (not the hostname but the actual VM name in VirtualBox)
    base.vm.provider "virtualbox" do |v|
      v.name = "punch-nat"
      # First we create the /tmp/mount directory with root owner and 777 permission
      v.customize "post-comm", ['guestcontrol', :id, 'run', '--exe', '/usr/bin/sudo', '--username', 'vagrant', '--password', 'vagrant', '--wait-stdout', '--wait-stderr', '--', 'sudo/arg0', '/bin/mkdir', '--mode', '777', '/tmp/mount']    
    end
    
    # Full upgrade of the system
    base.vm.provision :shell, run: "always", inline: "apt-get -y update && apt-get -y upgrade", privileged: true
    # Reload of the VM
    base.vm.provision :reload
    # Install some dependencies
    base.vm.provision :shell, path: "provision.sh"    
  end
end
