Vagrant.configure("2") do |config|

  config.vm.define "base_punch" do |base|
    base.vm.box = "envimation/ubuntu-xenial"
    # Install some dependencies
    base.vm.provision :shell, path: "provision.sh"
  end
end
