# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  # =====================================
  # Site A
  # =====================================

  # Node A1
  config.vm.define "node_a1" do |node_a1|
    node_a1.vm.box = "base-punch-nat"
    node_a1.vm.network "private_network", ip: "10.40.40.5", netmask: "255.255.255.0", virtualbox__intnet: true 
    node_a1.vm.hostname = "node-a1"    

    # Configuring Network Gateway for Node A1 in Site A
    # node_a1.vm.provision :shell, inline: "echo 'Configuring Network Gateway'", run: "always"
    # node_a1.vm.provision :shell, inline: "route del default gw 192.168.111.2 eth0 2>/dev/null || true", run: "always"
    # node_a1.vm.provision :shell, inline: "route add default gw 10.40.40.40 eth1 2>/dev/null || true", run: "always"
    # node_a1.vm.provision :shell, inline: "echo 'Network Gateway Configured'", run: "always"    

    node_a1.vm.provider "virtualbox" do |v|
      # v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      # v.customize ['modifyvm', :id, '--natdnsproxy1', 'on']      
      v.customize ['modifyvm', :id, '--intnet2', 'sitea']

      v.customize ['modifyvm', :id, '--natnet1', '192.168.111.0/24']
      v.customize ['modifyvm', :id, '--macaddress1', "5CA1AB1E0045"]
    end    
  end  

  # =====================================
  # Site B
  # =====================================

  # Node B1
  config.vm.define "node_b1" do |node_b1|
    node_b1.vm.box = "base-punch-nat"
    node_b1.vm.network "private_network", ip: "10.40.40.6", netmask: "255.255.255.0", virtualbox__intnet: true    
    node_b1.vm.hostname = "node-b1"

    # Configuring Network Gateway for Node B1 in Site B
    # node_b1.vm.provision :shell, inline: "echo 'Configuring Network Gateway'", run: "always"
    # node_b1.vm.provision :shell, inline: "route del default gw 192.168.222.2 eth0 2>/dev/null || true", run: "always"
    # node_b1.vm.provision :shell, inline: "route add default gw 10.40.40.40 eth1 2>/dev/null || true", run: "always"
    # node_b1.vm.provision :shell, inline: "echo 'Network Gateway Configured'", run: "always"    

    node_b1.vm.provider "virtualbox" do |v|
      # v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
      # v.customize ['modifyvm', :id, '--natdnsproxy1', 'on']         
      v.customize ['modifyvm', :id, '--intnet2', 'siteb']

      v.customize ['modifyvm', :id, '--natnet1', '192.168.222.0/24']
      v.customize ['modifyvm', :id, '--macaddress1', "5CA1AB1E0046"]      
    end    
  end  

end
